fatal: ERROR FATAL! Algo salió terriblemente mal!
error: Error! Algo no está bien!
warning: Advertencia! Prueba de Log warning!
fatal: ERROR FATAL! Algo salió terriblemente mal!
error: Error! Algo no está bien!
warning: Advertencia! Prueba de Log warning!
fatal: ERROR FATAL! Algo salió terriblemente mal!
error: Error! Algo no está bien!
warning: Advertencia! Prueba de Log warning!
warning: Error! Redireccionamos al login!
error: Usuario no autenticado, procediendo...
warning: Error! Redireccionamos al login!
error: Usuario no autenticado, procediendo...
warning: Error! Redireccionamos al login!
fatal: Credenciales inválidas!
fatal: Ups! Algo salio mal!:  next is not a function {"stack":"TypeError: next is not a function\n    at AuthController.login (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/auth.controller.js:31:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Usuario no autenticado, procediendo...
error: Usuario no autenticado, procediendo...
error: Usuario no autenticado, procediendo...
error: Usuario no autenticado, procediendo...
warning: Error! Redireccionamos al login!
error: Usuario no autenticado, procediendo...
warning: Error! Redireccionamos al login!
error: Usuario no autenticado, procediendo...
warning: Error! Redireccionamos al login!
error: Usuario no autenticado, procediendo...
warning: Error! Redireccionamos al login!
error: Usuario no autenticado, procediendo...
warning: Error! Redireccionamos al login!
error: Usuario no autenticado, procediendo...
warning: Error! Redireccionamos al login!
error: Usuario no autenticado, procediendo...
error: El usuario no tiene el rol necesario
error: Usuario no autenticado, procediendo...
error: Error al añadir producto, product: {"category":"accesorios","code":"1A2B3C","description":"Descripcion de prueba","id":11,"price":11111,"status":true,"stock":25,"thumbnail":["https://down-mx.img.susercontent.com/file/87091049e0aee0527ca1b68317b87a0e"],"title":"Titulo de prueba"}
error: Error al añadir producto, product: {"category":"accesorios","code":"1A2B3C","description":"Descripcion de prueba","price":11111,"status":true,"stock":25,"thumbnail":["https://down-mx.img.susercontent.com/file/87091049e0aee0527ca1b68317b87a0e"],"title":"Titulo de prueba"}
error: Error al añadir producto, product: {"category":"tipo de producto","code":"1A2B3CD","description":"Descripcion de prueba","id":12,"price":11111,"status":true,"stock":25,"thumbnail":["https://down-mx.img.susercontent.com/file/87091049e0aee0527ca1b68317b87a0e"],"title":"Titulo de prueba"}
error: Error personalizado capturado:  El producto no pudo ser encontrado {"code":404,"name":"Product not found","stack":"Product not found: El producto no pudo ser encontrado\n    at ProductController.getByID (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/products.controller.js:43:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Error personalizado capturado:  El producto no pudo ser encontrado {"code":404,"name":"Product not found","stack":"Product not found: El producto no pudo ser encontrado\n    at ProductController.getByID (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/products.controller.js:43:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Error personalizado capturado:  El producto no pudo ser encontrado {"code":404,"name":"Product not found","stack":"Product not found: El producto no pudo ser encontrado\n    at ProductController.getByID (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/products.controller.js:43:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Error personalizado capturado:  El producto no pudo ser encontrado {"code":404,"name":"Product not found","stack":"Product not found: El producto no pudo ser encontrado\n    at ProductController.getByID (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/products.controller.js:43:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: undefined
error: Error personalizado capturado:  El producto no pudo ser encontrado {"code":404,"name":"Product not found","stack":"Product not found: El producto no pudo ser encontrado\n    at ProductController.getByID (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/products.controller.js:43:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Usuario no autenticado, procediendo...
error: Usuario no autenticado, procediendo...
error: Usuario no autenticado, procediendo...
error: Usuario no autenticado, procediendo...
error: Usuario no autenticado, procediendo...
fatal: ERROR FATAL! Algo salió terriblemente mal!
error: Error! Algo no está bien!
warning: Advertencia! Prueba de Log warning!
error: Error personalizado capturado:  El producto no pudo ser encontrado {"code":404,"name":"Product not found","stack":"Product not found: El producto no pudo ser encontrado\n    at ProductController.getByID (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/products.controller.js:43:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Error personalizado capturado:  El producto no pudo ser encontrado {"code":404,"name":"Product not found","stack":"Product not found: El producto no pudo ser encontrado\n    at ProductController.getByID (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/products.controller.js:43:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Error personalizado capturado:  El producto no pudo ser encontrado {"code":404,"name":"Product not found","stack":"Product not found: El producto no pudo ser encontrado\n    at ProductController.getByID (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/products.controller.js:43:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Error personalizado capturado:  El producto no pudo ser encontrado {"code":404,"name":"Product not found","stack":"Product not found: El producto no pudo ser encontrado\n    at ProductController.getByID (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/products.controller.js:43:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Error personalizado capturado:  El producto no pudo ser encontrado {"code":404,"name":"Product not found","stack":"Product not found: El producto no pudo ser encontrado\n    at ProductController.getByID (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/products.controller.js:43:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Error personalizado capturado:  El producto no pudo ser encontrado {"code":404,"name":"Product not found","stack":"Product not found: El producto no pudo ser encontrado\n    at ProductController.getByID (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/products.controller.js:43:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Error al añadir producto, product: {"category":"Peluches","code":"cranidos884","description":"Este producto es original e importado de Japón, de la marca Banpresto año 2007, viene con todas sus etiquetas y mide 17cm de alto","price":15400,"status":true,"stock":30,"thumbnail":["https://acdn.mitiendanube.com/stores/110/201/products/cranidos1-602de7a3e09818128f16752666496389-640-0.webp"],"title":"Cranidos"}
error: Error al añadir producto, product: {"category":"Peluches","code":"squirtle003","description":"Este producto es original e importado de Japón, de la marca Banpresto año 2014, viene con todas sus etiquetas y mide 14cm de alto","price":13200,"status":true,"stock":35,"thumbnail":["https://acdn.mitiendanube.com/stores/110/201/products/20230831_1350491-48af8f88220935c28916935074042965-640-0.webp"],"title":"Squirtle"}
error: Error personalizado capturado:  El producto no pudo ser encontrado {"code":404,"name":"Product not found","stack":"Product not found: El producto no pudo ser encontrado\n    at ProductController.getByID (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/products.controller.js:43:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: undefined
error: undefined
warning: Error! Redireccionamos al login!
error: Usuario no autenticado, procediendo...
warning: Error! Redireccionamos al login!
error: Usuario no autenticado, procediendo...
error: undefined
error: El usuario no tiene el rol necesario
error: Usuario no autenticado, procediendo...
error: Error personalizado capturado:  El producto no pudo ser encontrado {"code":404,"name":"Product not found","stack":"Product not found: El producto no pudo ser encontrado\n    at ProductController.getByID (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/products.controller.js:43:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Error no manejado capturado: next is not a function {"stack":"TypeError: next is not a function\n    at UserController.current (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/user.controller.js:76:22)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/routes/sessions.router.js:39:17\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:30:5\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:15:7\n    at JwtStrategy.strategy.success (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport\\lib\\middleware\\authenticate.js:222:18)\n    at verified (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport-jwt\\lib\\strategy.js:115:41)"}
error: Error no manejado capturado: next is not a function {"stack":"TypeError: next is not a function\n    at UserController.current (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/user.controller.js:76:22)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/routes/sessions.router.js:39:17\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:30:5\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:15:7\n    at JwtStrategy.strategy.success (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport\\lib\\middleware\\authenticate.js:222:18)\n    at verified (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport-jwt\\lib\\strategy.js:115:41)"}
error: Error no manejado capturado: next is not a function {"stack":"TypeError: next is not a function\n    at UserController.current (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/user.controller.js:76:22)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/routes/sessions.router.js:39:17\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:30:5\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:15:7\n    at JwtStrategy.strategy.success (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport\\lib\\middleware\\authenticate.js:222:18)\n    at verified (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport-jwt\\lib\\strategy.js:115:41)"}
error: Usuario no autenticado, procediendo...
fatal: Credenciales inválidas!
fatal: Ups! Algo salio mal!:  next is not a function {"stack":"TypeError: next is not a function\n    at AuthController.login (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/auth.controller.js:31:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Usuario no autenticado, procediendo...
fatal: Credenciales inválidas!
fatal: Ups! Algo salio mal!:  next is not a function {"stack":"TypeError: next is not a function\n    at AuthController.login (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/auth.controller.js:31:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
error: Usuario no autenticado, procediendo...
error: Error no manejado capturado: next is not a function {"stack":"TypeError: next is not a function\n    at UserController.current (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/user.controller.js:76:22)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/routes/sessions.router.js:39:17\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:30:5\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:15:7\n    at JwtStrategy.strategy.success (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport\\lib\\middleware\\authenticate.js:222:18)\n    at verified (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport-jwt\\lib\\strategy.js:115:41)"}
error: Error no manejado capturado: next is not a function {"stack":"TypeError: next is not a function\n    at UserController.current (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/user.controller.js:76:22)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/routes/sessions.router.js:39:17\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:30:5\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:15:7\n    at JwtStrategy.strategy.success (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport\\lib\\middleware\\authenticate.js:222:18)\n    at verified (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport-jwt\\lib\\strategy.js:115:41)"}
error: Error no manejado capturado: next is not a function {"stack":"TypeError: next is not a function\n    at UserController.current (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/user.controller.js:76:22)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/routes/sessions.router.js:39:17\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:30:5\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:15:7\n    at JwtStrategy.strategy.success (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport\\lib\\middleware\\authenticate.js:222:18)\n    at verified (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport-jwt\\lib\\strategy.js:115:41)"}
error: Error no manejado capturado: next is not a function {"stack":"TypeError: next is not a function\n    at UserController.current (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/user.controller.js:76:22)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/routes/sessions.router.js:39:17\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:30:5\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:15:7\n    at JwtStrategy.strategy.success (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport\\lib\\middleware\\authenticate.js:222:18)\n    at verified (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport-jwt\\lib\\strategy.js:115:41)"}
error: Error no manejado capturado: next is not a function {"stack":"TypeError: next is not a function\n    at UserController.current (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/user.controller.js:76:22)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/routes/sessions.router.js:39:17\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:30:5\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:15:7\n    at JwtStrategy.strategy.success (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport\\lib\\middleware\\authenticate.js:222:18)\n    at verified (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport-jwt\\lib\\strategy.js:115:41)"}
error: Error no manejado capturado: next is not a function {"stack":"TypeError: next is not a function\n    at UserController.current (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/user.controller.js:76:22)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/routes/sessions.router.js:39:17\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:30:5\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:15:7\n    at JwtStrategy.strategy.success (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport\\lib\\middleware\\authenticate.js:222:18)\n    at verified (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport-jwt\\lib\\strategy.js:115:41)"}
error: Error no manejado capturado: next is not a function {"stack":"TypeError: next is not a function\n    at UserController.current (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/user.controller.js:76:22)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/routes/sessions.router.js:39:17\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:30:5\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:15:7\n    at JwtStrategy.strategy.success (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport\\lib\\middleware\\authenticate.js:222:18)\n    at verified (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport-jwt\\lib\\strategy.js:115:41)"}
error: Error no manejado capturado: next is not a function {"stack":"TypeError: next is not a function\n    at UserController.current (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/user.controller.js:76:22)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/routes/sessions.router.js:39:17\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:30:5\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:15:7\n    at JwtStrategy.strategy.success (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport\\lib\\middleware\\authenticate.js:222:18)\n    at verified (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport-jwt\\lib\\strategy.js:115:41)"}
error: Error no manejado capturado: next is not a function {"stack":"TypeError: next is not a function\n    at UserController.current (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/user.controller.js:76:22)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/routes/sessions.router.js:39:17\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:30:5\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:15:7\n    at JwtStrategy.strategy.success (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport\\lib\\middleware\\authenticate.js:222:18)\n    at verified (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport-jwt\\lib\\strategy.js:115:41)"}
error: Error no manejado capturado: next is not a function {"stack":"TypeError: next is not a function\n    at UserController.current (file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/controllers/user.controller.js:76:22)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/routes/sessions.router.js:39:17\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:30:5\n    at Layer.handle [as handle_request] (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at file:///E:/CODERHOUSE/BACKEND/Desafios%20entegrables/desafio/src/middleware/passportAuthorization.js:15:7\n    at JwtStrategy.strategy.success (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport\\lib\\middleware\\authenticate.js:222:18)\n    at verified (E:\\CODERHOUSE\\BACKEND\\Desafios entegrables\\desafio\\node_modules\\passport-jwt\\lib\\strategy.js:115:41)"}
